<?php
### WEBSITE CURRENCY CONFIGURATION
$GLOBALS['CURRENCY'] = "$" ;

### ADMINS IMAGE DIRECTORY
$GLOBALS['ADMINS_DIRECTORY'] = "public/uploads/admins/";

### SLIDER IMAGE DIRECTORY
$GLOBALS['SLIDES_DIRECTORY'] = "public/uploads/slides/";

### SUBCATEGORY BANNER IMAGE DIRECTORY
$GLOBALS['BANNER_DIRECTORY'] = "public/uploads/banners/";
?>
